const translations={
en:{
nav_checker:"Checker",nav_research:"Research",nav_solutions:"Solutions",nav_about:"About",eyebrow:"RAPID THREAT VERIFICATION",
hero_title:"Pause. Verify.<br><span>Protect yourself.</span>",hero_text:"Cyber-Shield is an interactive prototype that helps users assess suspicious calls, SMS messages, links and offers before they act.",
hero_button:"Check a contact",hero_research:"View our research",trust_database:"personal data stored",trust_scenarios:"demo scenarios",trust_levels:"risk levels",prototype:"INTERACTIVE PROTOTYPE",status_ready:"Ready to verify",
checker_eyebrow:"CONTACT CHECKER",checker_title:"What are you dealing with?",checker_text:"Choose the situation. The prototype will ask a few simple questions and give a preliminary risk level.",
bank_title:"Bank call",bank_desc:"Someone claims to be a bank employee.",sms_title:"SMS / message",sms_desc:"A message asks you to click, pay or verify.",link_title:"Suspicious link",link_desc:"A website or URL looks unusual.",offer_title:"Offer / investment",offer_desc:"Someone promises profit or urgent rewards.",
checker_note:"This is a research prototype, not a live fraud database. Never enter passwords, PINs, card numbers or SMS codes.",
research_eyebrow:"RESEARCH SNAPSHOT",research_title:"The problem is growing — and human behaviour matters.",research_text:"Our research combines statistical indicators, international comparison, literature review and analysis of existing solutions.",
stat1:"registered internet-fraud cases in 2024",stat2:"more cases than in H1 2024",stat2small:"Research presentation indicator",stat3:"FBI IC3 reported cybercrime losses in 2024",stat4:"of FTC fraud reporters lost money in 2024",stat4small:"27% reported losses in 2023",
insight1_title:"Social engineering",insight1_text:"Scammers exploit urgency, authority and emotional pressure. A technically secure device does not prevent a user from being manipulated.",insight2_title:"The usability gap",insight2_text:"Existing tools often focus on technical detection or post-incident response. Users need a simple decision aid at the critical moment.",insight3_title:"Explain, don't scare",insight3_text:"Literature reviewed by the team supports human-centred warnings: detect the risk, explain why, then guide the next action.",
solutions_eyebrow:"EXISTING SOLUTIONS",solutions_title:"Cyber-Shield connects the missing pieces.",solution:"Solution",purpose:"Purpose",strength:"Strength",limitation:"Limitation",
kz_purpose:"Incident response & guidance",kz_strength:"Official, free hotline 1400",kz_limit:"Not a simple real-time assistant",google_purpose:"Dangerous site / file warnings",google_strength:"Automated web protection",google_limit:"Web-focused, limited scam context",true_purpose:"Caller ID & spam warnings",true_strength:"Real-time call warnings",true_limit:"Focused mainly on calls",cs_purpose:"Rapid threat verification",cs_strength:"Simple, human-centred decision tree",cs_limit:"Prototype; no live database",
wf1:"Choose",wf1d:"Bank call, SMS, link or offer",wf2:"Answer",wf2d:"Simple button questions",wf3:"Risk level",wf3d:"Low · Careful · High",wf4:"Act",wf4d:"Stop · verify · report",
about_eyebrow:"PROJECT",about_text:"A university ICT research project focused on telephone and Internet scams. The concept is intentionally lightweight: HTML, CSS and JavaScript can demonstrate the decision tree without requiring a database or costly AI.",privacy:"Privacy first: the prototype does not ask for passwords, PINs, card details or verification codes.",emergency:"IF MONEY IS STOLEN",emergency_text:"Contact your bank immediately, then report the incident to the appropriate authorities. Cyber-Shield supports — but does not replace — banks, police and CERTs.",footer:"Research prototype · Preliminary risk assessment only"
},
ru:{
nav_checker:"Проверка",nav_research:"Исследование",nav_solutions:"Решения",nav_about:"О проекте",eyebrow:"БЫСТРАЯ ПРОВЕРКА УГРОЗ",
hero_title:"Остановись. Проверь.<br><span>Защити себя.</span>",hero_text:"Cyber-Shield — интерактивный прототип для оценки подозрительных звонков, SMS, ссылок и предложений до того, как пользователь совершит действие.",
hero_button:"Проверить контакт",hero_research:"Наше исследование",trust_database:"персональных данных сохранено",trust_scenarios:"демо-сценария",trust_levels:"уровня риска",prototype:"ИНТЕРАКТИВНЫЙ ПРОТОТИП",status_ready:"Готов к проверке",
checker_eyebrow:"ПРОВЕРКА КОНТАКТА",checker_title:"С чем вы столкнулись?",checker_text:"Выберите ситуацию. Прототип задаст несколько простых вопросов и покажет предварительный уровень риска.",
bank_title:"Звонок из банка",bank_desc:"Человек представляется сотрудником банка.",sms_title:"SMS / сообщение",sms_desc:"Сообщение просит перейти, оплатить или подтвердить действие.",link_title:"Подозрительная ссылка",link_desc:"Сайт или URL выглядит необычно.",offer_title:"Предложение / инвестиции",offer_desc:"Кто-то обещает прибыль или требует срочного решения.",
checker_note:"Это исследовательский прототип, а не актуальная база мошенников. Никогда не вводите пароли, PIN, данные карты или SMS-коды.",
research_eyebrow:"РЕЗУЛЬТАТЫ ИССЛЕДОВАНИЯ",research_title:"Проблема растёт — и человеческий фактор имеет значение.",research_text:"Исследование объединяет статистические показатели, международное сравнение, обзор литературы и анализ существующих решений.",
stat1:"зарегистрированных случаев интернет-мошенничества в 2024 году",stat2:"больше случаев, чем в I полугодии 2024",stat2small:"Показатель из презентации проекта",stat3:"заявленные FBI IC3 потери от киберпреступности в 2024 году",stat4:"сообщивших о мошенничестве потеряли деньги в 2024",stat4small:"27% сообщили о потерях в 2023",
insight1_title:"Социальная инженерия",insight1_text:"Мошенники используют срочность, авторитет и эмоциональное давление. Даже защищённое устройство не мешает манипулировать человеком.",insight2_title:"Пробел в удобстве",insight2_text:"Существующие инструменты часто сосредоточены на техническом обнаружении или реагировании после инцидента. Пользователю нужна простая подсказка в критический момент.",insight3_title:"Объяснять, а не пугать",insight3_text:"Изученная командой литература поддерживает человеко-ориентированные предупреждения: обнаружить риск, объяснить причину и подсказать действие.",
solutions_eyebrow:"СУЩЕСТВУЮЩИЕ РЕШЕНИЯ",solutions_title:"Cyber-Shield объединяет недостающие элементы.",solution:"Решение",purpose:"Назначение",strength:"Сильная сторона",limitation:"Ограничение",
kz_purpose:"Реагирование и рекомендации",kz_strength:"Официальная бесплатная линия 1400",kz_limit:"Не простой помощник в реальном времени",google_purpose:"Предупреждения о вредных сайтах/файлах",google_strength:"Автоматическая веб-защита",google_limit:"Ориентирован на веб, мало контекста мошенничества",true_purpose:"Определитель номера и спам",true_strength:"Предупреждения в реальном времени",true_limit:"В основном звонки",cs_purpose:"Быстрая проверка угроз",cs_strength:"Простое человеко-ориентированное дерево решений",cs_limit:"Прототип; без актуальной базы",
wf1:"Выбрать",wf1d:"Звонок, SMS, ссылка или предложение",wf2:"Ответить",wf2d:"Простые вопросы-кнопки",wf3:"Уровень риска",wf3d:"Низкий · Внимание · Высокий",wf4:"Действовать",wf4d:"Остановиться · проверить · сообщить",
about_eyebrow:"ПРОЕКТ",about_text:"Университетский ICT-проект об телефонном и интернет-мошенничестве. Концепция специально сделана лёгкой: HTML, CSS и JavaScript позволяют показать дерево решений без базы данных и дорогого ИИ.",privacy:"Приватность прежде всего: прототип не запрашивает пароли, PIN, данные карты или коды подтверждения.",emergency:"ЕСЛИ ДЕНЬГИ УКРАДЕНЫ",emergency_text:"Немедленно свяжитесь с банком, затем сообщите об инциденте в соответствующие органы. Cyber-Shield поддерживает, но не заменяет банки, полицию и CERT.",footer:"Исследовательский прототип · Только предварительная оценка риска"
},
kk:{
nav_checker:"Тексеру",nav_research:"Зерттеу",nav_solutions:"Шешімдер",nav_about:"Жоба",eyebrow:"ҚАУІПТІ ЖЕДЕЛ ТЕКСЕРУ",
hero_title:"Тоқта. Тексер.<br><span>Өзіңді қорға.</span>",hero_text:"Cyber-Shield — күдікті қоңырауларды, SMS, сілтемелерді және ұсыныстарды әрекет жасамас бұрын бағалауға көмектесетін интерактивті прототип.",
hero_button:"Контактіні тексеру",hero_research:"Зерттеуді көру",trust_database:"жеке дерек сақталмайды",trust_scenarios:"демо сценарий",trust_levels:"қауіп деңгейі",prototype:"ИНТЕРАКТИВТІ ПРОТОТИП",status_ready:"Тексеруге дайын",
checker_eyebrow:"КОНТАКТІНІ ТЕКСЕРУ",checker_title:"Қандай жағдайға тап болдыңыз?",checker_text:"Жағдайды таңдаңыз. Прототип бірнеше қарапайым сұрақ қойып, алдын ала қауіп деңгейін көрсетеді.",
bank_title:"Банк қоңырауы",bank_desc:"Біреу өзін банк қызметкері ретінде таныстырды.",sms_title:"SMS / хабарлама",sms_desc:"Хабарлама сілтемеге өтуді, төлеуді немесе растауды сұрайды.",link_title:"Күдікті сілтеме",link_desc:"Сайт немесе URL әдеттен тыс көрінеді.",offer_title:"Ұсыныс / инвестиция",offer_desc:"Біреу пайдаға немесе шұғыл сыйақыға уәде береді.",
checker_note:"Бұл — зерттеу прототипі, нақты алаяқтар базасы емес. Құпиясөз, PIN, карта деректері немесе SMS кодтарын енгізбеңіз.",
research_eyebrow:"ЗЕРТТЕУ НӘТИЖЕСІ",research_title:"Мәселе өсіп келеді — адам факторы маңызды.",research_text:"Зерттеу статистика, халықаралық салыстыру, ғылыми әдебиеттер шолуы және қолданыстағы шешімдерді талдауды біріктіреді.",
stat1:"2024 жылы тіркелген интернет-алаяқтық жағдайы",stat2:"2024 жылдың I жартыжылдығымен салыстырғандағы өсім",stat2small:"Жоба презентациясындағы көрсеткіш",stat3:"2024 жылы FBI IC3 тіркеген киберқылмыс шығыны",stat4:"2024 жылы алаяқтық туралы хабарлағандардың ақша жоғалтқан үлесі",stat4small:"2023 жылы — 27%",
insight1_title:"Әлеуметтік инженерия",insight1_text:"Алаяқтар асығыстықты, беделді және эмоциялық қысымды пайдаланады. Құрылғының техникалық қорғанысы адамды манипуляциядан толық қорғамайды.",insight2_title:"Қарапайымдылық тапшылығы",insight2_text:"Қолданыстағы құралдар техникалық анықтауға немесе оқиғадан кейінгі әрекетке бағытталған. Адамға шешім қабылдайтын сәтте қарапайым көмек қажет.",insight3_title:"Қорқытпай, түсіндіру",insight3_text:"Зерттелген әдебиеттер адамға бағытталған ескертулерді қолдайды: қауіпті анықтау, себебін түсіндіру және келесі әрекетті көрсету.",
solutions_eyebrow:"ҚОЛДАНЫСТАҒЫ ШЕШІМДЕР",solutions_title:"Cyber-Shield жетіспейтін бөліктерді біріктіреді.",solution:"Шешім",purpose:"Мақсаты",strength:"Артықшылығы",limitation:"Шектеуі",
kz_purpose:"Оқиғаға жауап және кеңес",kz_strength:"Ресми, тегін 1400 желісі",kz_limit:"Нақты уақыттағы қарапайым көмекші емес",google_purpose:"Қауіпті сайттар мен файлдар туралы ескерту",google_strength:"Автоматты веб-қорғаныс",google_limit:"Вебке бағытталған, алаяқтық контексті шектеулі",true_purpose:"Нөмірді анықтау және спам",true_strength:"Нақты уақыттағы ескерту",true_limit:"Негізінен қоңырауларға бағытталған",cs_purpose:"Қауіпті жедел тексеру",cs_strength:"Қарапайым адамға бағытталған шешім ағашы",cs_limit:"Прототип; нақты дерекқор жоқ",
wf1:"Таңдау",wf1d:"Банк қоңырауы, SMS, сілтеме немесе ұсыныс",wf2:"Жауап беру",wf2d:"Қарапайым батырма сұрақтары",wf3:"Қауіп деңгейі",wf3d:"Төмен · Абай бол · Жоғары",wf4:"Әрекет",wf4d:"Тоқта · тексер · хабарла",
about_eyebrow:"ЖОБА",about_text:"Телефон және интернет алаяқтығына арналған университеттік ICT зерттеу жобасы. HTML, CSS және JavaScript көмегімен шешім ағашын дерекқорсыз және қымбат AI-сыз көрсетуге болады.",privacy:"Құпиялылық бірінші орында: прототип құпиясөз, PIN, карта деректері немесе растау кодтарын сұрамайды.",emergency:"ЕГЕР АҚША ҰРЛАНСА",emergency_text:"Банкке дереу хабарласыңыз, кейін тиісті органдарға хабарлаңыз. Cyber-Shield банктерді, полицияны және CERT қызметтерін қолдайды, бірақ оларды алмастырмайды.",footer:"Зерттеу прототипі · Тек алдын ала қауіп бағасы"
}};
const scenarios={
bank:{title:{en:"Bank call",ru:"Звонок из банка",kk:"Банк қоңырауы"},questions:[
{q:{en:"Did the caller ask for a password, PIN, SMS code or card details?",ru:"Звонивший попросил пароль, PIN, SMS-код или данные карты?",kk:"Қоңырау шалушы құпиясөз, PIN, SMS коды немесе карта деректерін сұрады?"},yes:3,no:0},
{q:{en:"Did they create urgency or threaten to block your account?",ru:"Вас торопили или угрожали заблокировать счёт?",kk:"Сізді асықтырды немесе шотыңызды бұғаттаймыз деп қорқытты ма?"},yes:2,no:0},
{q:{en:"Can you independently call the bank using the official number?",ru:"Вы можете сами перезвонить в банк по официальному номеру?",kk:"Банктің ресми нөміріне өзіңіз қайта қоңырау шала аласыз ба?"},yes:0,no:2}]},
sms:{title:{en:"SMS / message",ru:"SMS / сообщение",kk:"SMS / хабарлама"},questions:[
{q:{en:"Does the message ask you to click a link or open an attachment?",ru:"Сообщение просит перейти по ссылке или открыть вложение?",kk:"Хабарлама сілтемеге өтуді немесе тіркемені ашуды сұрай ма?"},yes:2,no:0},
{q:{en:"Does it demand urgent payment, verification or a transfer?",ru:"Требуется срочная оплата, подтверждение или перевод?",kk:"Шұғыл төлем, растау немесе ақша аудару талап етіле ме?"},yes:2,no:0},
{q:{en:"Were you expecting this message from a service you already use?",ru:"Вы ожидали это сообщение от сервиса, которым пользуетесь?",kk:"Бұл хабарламаны қолданып жүрген қызметтен күттіңіз бе?"},yes:0,no:1}]},
link:{title:{en:"Suspicious link",ru:"Подозрительная ссылка",kk:"Күдікті сілтеме"},questions:[
{q:{en:"Does the URL contain unusual spelling, extra words or a strange domain?",ru:"В URL есть необычное написание, лишние слова или странный домен?",kk:"URL ішінде қате жазу, артық сөздер немесе күдікті домен бар ма?"},yes:2,no:0},
{q:{en:"Did the link arrive unexpectedly or from an unknown sender?",ru:"Ссылка пришла неожиданно или от неизвестного отправителя?",kk:"Сілтеме күтпеген жерден немесе белгісіз жіберушіден келді ме?"},yes:2,no:0},
{q:{en:"Is the page asking for credentials, payment or a verification code?",ru:"Страница просит логин, оплату или код подтверждения?",kk:"Бет логин, төлем немесе растау кодын сұрай ма?"},yes:3,no:0}]},
offer:{title:{en:"Offer / investment",ru:"Предложение / инвестиции",kk:"Ұсыныс / инвестиция"},questions:[
{q:{en:"Are you promised unusually high or guaranteed returns?",ru:"Вам обещают необычно высокую или гарантированную доходность?",kk:"Сізге әдеттен тыс жоғары немесе кепілдендірілген табыс уәде етілді ме?"},yes:2,no:0},
{q:{en:"Are you pressured to decide or transfer money immediately?",ru:"Вас заставляют решить или перевести деньги немедленно?",kk:"Сізді бірден шешім қабылдауға немесе ақша аударуға мәжбүрлей ме?"},yes:2,no:0},
{q:{en:"Can you independently verify the company through official sources?",ru:"Вы можете независимо проверить компанию через официальные источники?",kk:"Компанияны ресми дереккөздер арқылы өзіңіз тексере аласыз ба?"},yes:0,no:2}]}
};
let currentLang="en",currentScenario=null,currentQ=0,score=0;
const text=(k)=>translations[currentLang][k]||k;
function applyLanguage(lang){currentLang=lang;document.querySelectorAll("[data-i18n]").forEach(el=>{const k=el.dataset.i18n;if(translations[lang][k]!==undefined)el.innerHTML=translations[lang][k]});document.querySelectorAll(".lang").forEach(b=>b.classList.toggle("active",b.dataset.lang===lang));if(currentScenario)renderQuestion()}
document.querySelectorAll(".lang").forEach(b=>b.addEventListener("click",()=>applyLanguage(b.dataset.lang)));
const modal=document.getElementById("modal");
function openModal(){modal.classList.remove("hidden")}
function closeModal(){modal.classList.add("hidden")}
document.getElementById("closeModal").addEventListener("click",closeModal);
document.querySelector(".modal-backdrop").addEventListener("click",closeModal);
document.querySelectorAll(".scenario").forEach(btn=>btn.addEventListener("click",()=>{currentScenario=btn.dataset.scenario;currentQ=0;score=0;renderQuestion();openModal()}));
function renderQuestion(){const s=scenarios[currentScenario],q=s.questions[currentQ],total=s.questions.length;document.getElementById("stepLabel").textContent=currentLang==="ru"?`Шаг ${currentQ+1} из ${total}`:currentLang==="kk"?`Қадам ${currentQ+1} / ${total}`:`Step ${currentQ+1} of ${total}`;document.getElementById("stepPercent").textContent=`${Math.round((currentQ+1)/total*100)}%`;document.getElementById("progressBar").style.width=`${(currentQ+1)/total*100}%`;const yes=currentLang==="ru"?"Да":currentLang==="kk"?"Иә":"Yes",no=currentLang==="ru"?"Нет":currentLang==="kk"?"Жоқ":"No";document.getElementById("modalBody").innerHTML=`<div class="eyebrow">CYBER-SHIELD / CHECK</div><h3>${s.title[currentLang]}</h3><p>${q.q[currentLang]}</p><div class="q-options"><button class="q-option" onclick="answer(true)">✓ ${yes}</button><button class="q-option" onclick="answer(false)">× ${no}</button></div><p style="margin-top:18px;font-size:10px;color:#5e746d">${currentLang==="ru"?"Не вводите реальные данные в этот прототип.":currentLang==="kk"?"Бұл прототипке нақты деректерді енгізбеңіз.":"Do not enter real personal data into this prototype."}</p>`}
window.answer=(yes)=>{score+=yes?scenarios[currentScenario].questions[currentQ].yes:scenarios[currentScenario].questions[currentQ].no;currentQ++;currentQ<scenarios[currentScenario].questions.length?renderQuestion():showResult()};
function showResult(){let level,title,textResult,actions;if(score>=5){level="high";title={en:"High risk",ru:"Высокий риск",kk:"Жоғары қауіп"}[currentLang];textResult={en:"Stop the interaction. Do not send money or disclose codes. Verify through an official channel.",ru:"Остановите взаимодействие. Не переводите деньги и не сообщайте коды. Проверьте ситуацию через официальный канал.",kk:"Әрекетті тоқтатыңыз. Ақша аудармаңыз және кодтарды айтпаңыз. Ресми арна арқылы тексеріңіз."}[currentLang];actions={en:["End the call / close the page","Call the organisation using its official number","If money was sent, contact your bank immediately"],ru:["Завершите звонок / закройте страницу","Позвоните в организацию по официальному номеру","Если деньги отправлены — немедленно свяжитесь с банком"],kk:["Қоңырауды аяқтаңыз / бетті жабыңыз","Ұйымға ресми нөмірі арқылы өзіңіз қоңырау шалыңыз","Ақша аударылса — банкке дереу хабарласыңыз"]}[currentLang]}else if(score>=3){level="careful";title={en:"Careful",ru:"Требует внимания",kk:"Абай болыңыз"}[currentLang];textResult={en:"There are warning signs. Pause and verify independently before doing anything.",ru:"Есть признаки риска. Остановитесь и самостоятельно проверьте источник до любых действий.",kk:"Қауіп белгілері бар. Әрекет жасамас бұрын тоқтап, дереккөзді өзіңіз тексеріңіз."}[currentLang];actions={en:["Do not use links or phone numbers from the message","Find the organisation's official website yourself","Never share passwords, PINs or SMS codes"],ru:["Не используйте ссылки и номера из сообщения","Самостоятельно найдите официальный сайт организации","Никогда не сообщайте пароли, PIN и SMS-коды"],kk:["Хабарламадағы сілтемелер мен нөмірлерді қолданбаңыз","Ұйымның ресми сайтын өзіңіз табыңыз","Құпиясөз, PIN және SMS кодтарын айтпаңыз"]}[currentLang]}else{level="low";title={en:"Lower risk — stay alert",ru:"Низкий риск — сохраняйте бдительность",kk:"Төмен қауіп — сақ болыңыз"}[currentLang];textResult={en:"No strong warning signs were detected by this simple prototype. This does not mean the contact is completely safe.",ru:"Прототип не обнаружил сильных признаков риска. Это не означает, что контакт полностью безопасен.",kk:"Прототип күшті қауіп белгілерін анықтаған жоқ. Бұл контакт толығымен қауіпсіз дегенді білдірмейді."}[currentLang];actions={en:["Continue carefully","Verify through an independent official channel if unsure","Never disclose authentication codes"],ru:["Продолжайте осторожно","При сомнениях проверьте через независимый официальный канал","Никому не сообщайте коды подтверждения"],kk:["Абайлап жалғастырыңыз","Күмән болса, тәуелсіз ресми арна арқылы тексеріңіз","Растау кодтарын ешкімге айтпаңыз"]}[currentLang]}
document.getElementById("modalBody").innerHTML=`<div class="eyebrow">CYBER-SHIELD / RESULT</div><h3>${scenarios[currentScenario].title[currentLang]}</h3><div class="result ${level}"><div class="result-tag">${title.toUpperCase()}</div><h4>${textResult}</h4><ul>${actions.map(a=>`<li>${a}</li>`).join("")}</ul></div><div class="modal-actions"><button class="mini-btn" onclick="restartCheck()">${currentLang==="ru"?"Пройти снова":currentLang==="kk"?"Қайта тексеру":"Check again"}</button><button class="mini-btn" onclick="closeModal()">${currentLang==="ru"?"Закрыть":currentLang==="kk"?"Жабу":"Close"}</button></div><p style="margin-top:20px;font-size:10px;color:#5e746d">${currentLang==="ru"?"Предварительная оценка. Прототип не подключён к базе данных и не заменяет банк, полицию или CERT.":currentLang==="kk"?"Алдын ала бағалау. Прототип дерекқорға қосылмаған және банк, полиция немесе CERT қызметтерін алмастырмайды.":"Preliminary assessment. The prototype has no live database and does not replace a bank, police or CERT."}</p>`;document.getElementById("stepLabel").textContent=currentLang==="ru"?"Готово":currentLang==="kk"?"Дайын":"Complete";document.getElementById("stepPercent").textContent="100%";document.getElementById("progressBar").style.width="100%"}
window.restartCheck=()=>{currentQ=0;score=0;renderQuestion()};
applyLanguage("en");